<?php $title = 'CRYBO | NFTs';
$addlink = '<link rel=”stylesheet” href=”css/grid-gallery.min.css”>';
include '../inc/head.php'; ?>

<body class="smooth-transition">
    <div class="container-fluid">

        <?php $nft = 'true';
        $product = 'ture';
        include '../inc/header.php'; ?>

        <section class="hero text-center">
            <h1>NFTs</h1>
            <hr class="nft-hr">
            <div class="container">
                <div class="row">
                    <div class="nft-div col-md-6">
                        <h2 class="nft-h2">Gallery</h2>
                        <p>
                        <h3 id="nft-infomation">This NFT is created with the theme of the fusion of snowboarding and NFT.<br>It is generated by an algorithm using Javascript so no 2 designs will be the same.<br>In the future, we will fuse Metaverse and snowboarding to create a new style of snowboarding.</h3>
                        <h3 id="nft-infomation"><br>Collection : <a href="https://opensea.io/collection/crybo-art">Generative Art by CRYBO</a></h3>
                        <h3 id="nft-infomation">Items : 41</h3>
                        <h3 id="nft-infomation">Chain : Polygon</h3>
                    </div>
                </div>
            </div>
        </section>
        <section class="nft-section hero">
            <hr class="nft-hr">
        </section>
        <section class="nft-container">
            <div id="gg-screen" hidden> </div>
            <div class="gg-box">

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/1.jpg">
                    <p class="nft-number">No. 1</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/0">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/2.jpg">
                    <p class="nft-number">No. 2</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/1">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/3.jpg">
                    <p class="nft-number">No. 3</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/2">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/4.jpg">
                    <p class="nft-number">No. 4</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/3">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/5.jpg">
                    <p class="nft-number">No. 5</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/4">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/6.jpg">
                    <p class="nft-number">No. 6</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/5">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/7.jpg">
                    <p class="nft-number">No. 7</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/6">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/8.jpg">
                    <p class="nft-number">No. 8</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/7">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/9.jpg">
                    <p class="nft-number">No. 9</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/8">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/10.jpg">
                    <p class="nft-number">No. 10</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/9">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/11.jpg">
                    <p class="nft-number">No. 11</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/10">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/12.jpg">
                    <p class="nft-number">No. 12</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/11">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/13.jpg">
                    <p class="nft-number">No. 13</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/12">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/14.jpg">
                    <p class="nft-number">No. 14</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/13">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/15.jpg">
                    <p class="nft-number">No. 15</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/14">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/16.jpg">
                    <p class="nft-number">No. 16</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/15">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/17.jpg">
                    <p class="nft-number">No. 17</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/16">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/18.jpg">
                    <p class="nft-number">No. 18</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/17">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/19.jpg">
                    <p class="nft-number">No. 19</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/18">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/20.jpg">
                    <p class="nft-number">No. 20</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/19">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/21.jpg">
                    <p class="nft-number">No. 21</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/20">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/22.jpg">
                    <p class="nft-number">No. 22</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/21">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/23.jpg">
                    <p class="nft-number">No. 23</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/22">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/24.jpg">
                    <p class="nft-number">No. 24</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/23">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/25.jpg">
                    <p class="nft-number">No. 25</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/24">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/26.jpg">
                    <p class="nft-number">No. 26</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/25">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/27.jpg">
                    <p class="nft-number">No. 27</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/26">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/28.jpg">
                    <p class="nft-number">No. 28</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/27">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/29.jpg">
                    <p class="nft-number">No. 29</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/28">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/30.jpg">
                    <p class="nft-number">No. 30</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/29">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/31.jpg">
                    <p class="nft-number">No. 31</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/30">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/32.jpg">
                    <p class="nft-number">No. 32</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/31">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/33.jpg">
                    <p class="nft-number">No. 33</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/32">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/34.jpg">
                    <p class="nft-number">No. 34</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/33">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/35.jpg">
                    <p class="nft-number">No. 35</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/34">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/36.jpg">
                    <p class="nft-number">No. 36</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/35">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/37.jpg">
                    <p class="nft-number">No. 37</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/36">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/38.jpg">
                    <p class="nft-number">No. 38</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/37">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/39.jpg">
                    <p class="nft-number">No. 39</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/38">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/40.jpg">
                    <p class="nft-number">No. 40</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/39">Buy in OpenSea</a>
                </div>

                <div class="nft-image-container">
                    <img id="nft-image" src="/images/nft/41.jpg">
                    <p class="nft-number">No. 41</p>
                    <a class="btn nft-opensea-btn" href="https://opensea.io/ja/assets/matic/0xb4f200da626b10e07427b69d957430aa8ed32124/40">Buy in OpenSea</a>
                </div>

            </div>
            <hr class="nft-hr nft-hr-bottom">
        </section>

        <?php include '../inc/footer.php'; ?>
    </div>
    <?php include '../inc/script.php'; ?>
</body>

</html>
